# Generated by Django 4.2.1 on 2023-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('images', models.ImageField(upload_to='media')),
                ('desc', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'Pet',
            },
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
