# Generated by Django 4.2.1 on 2023-06-09 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_birds_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Layoff',
            fields=[
                ('staff_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='myapp.staff')),
                ('language', models.CharField(max_length=20)),
            ],
        ),
    ]
