# Generated by Django 4.2.1 on 2023-06-09 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='number',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
